server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: student-service
          uri: http://student-service:8081
          predicates:
            - Path=/students/**
        - id: teacher-service
          uri: http://teacher-service:8082
          predicates:
            - Path=/teachers/**